CREATE TABLE [User] 
(
	UserId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	FirstName NVARCHAR(50),
	LastName NVARCHAR(50),
	Email NVARCHAR(100) NOT NULL,
	PhoneNumber NVARCHAR(15),
	[Password] NVARCHAR(50) NOT NULL
)

CREATE TABLE Book 
(
	BookId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	[Description] TEXT NOT NULL, 
	UserId INT NOT NULL 
		FOREIGN KEY (UserId) REFERENCES [User](UserId) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE
)

CREATE TABLE Recipe 
(
	RecipeId INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	Title NVARCHAR(100) NOT NULL,
	Ingredients TEXT NOT NULL,
	Instructions TEXT NOT NULL,
	BookId INT NOT NULL
		FOREIGN KEY (BookId) REFERENCES Book(BookId) 
		ON DELETE CASCADE 
		ON UPDATE CASCADE
)